Branch one
Surabhi2011/Training_1 pull request #1
Opened 2019-09-12 06:16 UTC by Surabhi2011

2019-09-12 06:23 UTC, bhaskar211 commented on src/test/java/org/shl/testng/SHL_Prj1/TestScript.java
> +
no need

2019-09-17 09:41 UTC, kartikbawa-prog commented on .settings/org.eclipse.jdt.core.prefs
>  eclipse.preferences.version=1
remove this

2019-09-17 09:47 UTC, kartikbawa-prog commented on src/main/java/Pages/Camera.java
> +public class Camera extends BaseClass{
change Name of class as variables and functions are not specific to Camera.

2019-09-17 09:47 UTC, kartikbawa-prog commented on src/main/java/Pages/Camera.java
> +	WebDriver driver;
make instance variables private

2019-09-17 09:48 UTC, kartikbawa-prog commented on src/main/java/Pages/Camera.java
> +	public By Compare=By.xpath("//span[text()='COMPARE']");
keep all instance variables together at top

2019-09-17 09:51 UTC, kartikbawa-prog commented on src/main/java/Pages/Compare.java
> +		Product=driver.findElement(By.xpath("//*[@id=\"fk-compare-page\"]/div/div/div/div[1]/div[2]/div/div[1]/div[1]/div["+i+"]")).getText();
Find better xpaths

2019-09-17 09:51 UTC, kartikbawa-prog commented on src/main/java/Pages/Compare.java
> +	System.out.println(LowProduct);
use logs instead

2019-09-17 09:52 UTC, kartikbawa-prog commented on src/main/java/Pages/HomePage.java
> +	public By CancelPopUp=By.xpath("//button[text()='✕']");
make them private

2019-09-17 09:54 UTC, kartikbawa-prog commented on src/main/java/Pages/HomePage.java
> +		try {
handle pop up properly

2019-09-17 09:55 UTC, kartikbawa-prog commented on src/main/java/Pages/HomePage.java
> +	public By Electronics=By.xpath("//span[text()='Electronics']");
follow naming convention

2019-09-17 09:57 UTC, kartikbawa-prog commented on src/main/java/Pages/ProductPage.java
> +			try{
dont use try-catch as if-else

2019-09-17 10:05 UTC, kartikbawa-prog commented on src/main/java/Pages/ProductPage.java
> +				System.out.println("Product Name: "+ProductName+"\nProduct Ratings: "+NumberOfRatings+"\nProduct StarRating: "+starrating);
logs

2019-09-17 10:22 UTC, kartikbawa-prog commented on src/main/java/utilities/BaseClass.java
> +	                            wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
change this

2019-09-17 10:26 UTC, kartikbawa-prog commented on src/main/java/utilities/Initialiser.java
> +    	try {
handle exceptions properly

2019-09-17 10:30 UTC, kartikbawa-prog commented on src/main/java/utilities/Product.java
> +package utilities;
remove as it is not used

2019-09-17 10:32 UTC, kartikbawa-prog commented on src/test/java/org/shl/testng/SHL_Prj1/TestScript2.java
> +		cameraPage.addtoCompare(3);
put hardcoded value in CONSTANTS

2019-09-17 10:39 UTC, kartikbawa-prog requested changes
Add better comments.
Take care of access modifiers.
and make other mentioned changes

2019-09-18 05:44 UTC, closed without merging

2019-09-18 06:02 UTC, grajput380 requested changes

2019-09-18 06:02 UTC, grajput380 commented on src/main/java/Pages/HomePage.java
> +		Actions act = new Actions(driver);
please create common method to use actions class

2019-09-18 06:02 UTC, grajput380 commented on src/main/java/Pages/HomePage.java
> +		waitCondition(condition.ELEMENT_TO_BE_CLICKABLE,CameraAcc,driver,10);
do we need to pass driver for this method ? I think driver is already available in BaseClass

2019-09-18 06:02 UTC, grajput380 commented on src/main/java/utilities/Initialiser.java
> +    	productPage=new ProductPage(driver,wait);
please find a better approach to create object of pages